services:
  core-api:
    build:
      context: ./core-api
      dockerfile: Dockerfile
      target: development
    ports:
      - "4000:3000" # On utilise à nouveau le port 4000 pour Windows
    volumes:
      - ./core-api:/app
      - /app/node_modules
      - /app/dist
    env_file:
      - ./core-api/.env
    networks:
      - kayydrive-network

  ia-service:
    build:
      context: ./ia-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ia-service:/app
    networks:
      - kayydrive-network

  osrm-backend:
    image: osrm/osrm-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: osrm-routed --algorithm mld /data/cameroon-latest.osrm
    networks:
      - kayydrive-network

networks:
  kayydrive-network:
    driver: bridge
