sonar.projectKey=lionel-youassa
sonar.organization=lionel-youassa
sonar.projectName=KayyDrive Backend
sonar.projectVersion=1.0.0

sonar.sources=core-api/src
sonar.tests=core-api/src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.dto.ts

sonar.typescript.lcov.reportPaths=core-api/coverage/lcov.info

sonar.sourceEncoding=UTF-8
